const { pool } = require('../config/db');

const ddl = `
-- Drop existing tables if they exist to ensure clean schema
DROP TABLE IF EXISTS tracking_gps CASCADE;
DROP TABLE IF EXISTS detail_permohonan CASCADE;
DROP TABLE IF EXISTS permohonan CASCADE;
DROP TABLE IF EXISTS barang CASCADE;
DROP TABLE IF EXISTS tugas CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. Tabel Users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_lengkap TEXT NOT NULL,
    role TEXT CHECK (role IN ('pimpinan', 'teknisi', 'gudang')) NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

-- 2. Tabel Tugas
CREATE TABLE tugas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pimpinan_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    teknisi_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    jenis_kerja TEXT NOT NULL, -- 'Pasang Baru', 'Gangguan', 'ODP'
    lokasi TEXT NOT NULL,
    status TEXT DEFAULT 'Open', -- 'Open', 'Progress', 'Done'
    foto_bukti TEXT
);

-- 3. Tabel Barang
CREATE TABLE barang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_barang TEXT NOT NULL,
    stok INT NOT NULL DEFAULT 0,
    satuan TEXT NOT NULL -- 'roll', 'pcs', 'meter'
);

-- 4. Tabel Permohonan
CREATE TABLE permohonan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tugas_id BIGINT REFERENCES tugas(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'Pending', -- 'Pending', 'Approved', 'Released'
    waktu_request TIMESTAMP DEFAULT NOW()
);

-- 5. Tabel Detail Permohonan
CREATE TABLE detail_permohonan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permohonan_id BIGINT REFERENCES permohonan(id) ON DELETE CASCADE,
    barang_id BIGINT REFERENCES barang(id) ON DELETE CASCADE,
    jumlah_minta INT NOT NULL
);

-- 6. Tabel Tracking GPS
CREATE TABLE tracking_gps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tugas_id BIGINT REFERENCES tugas(id) ON DELETE CASCADE,
    latitude FLOAT8 NOT NULL,
    longitude FLOAT8 NOT NULL,
    waktu_update TIMESTAMP DEFAULT NOW()
);

-- Seed Data Akun Dummy
INSERT INTO users (nama_lengkap, role, email, password) VALUES
('Pimpinan STO', 'pimpinan', 'admin@sto.telkom.co.id', 'admin123'),
('Ari', 'teknisi', 'ari@sto.telkom.co.id', 'teknisi123'),
('Petugas Gudang', 'gudang', 'gudang@sto.telkom.co.id', 'gudang123');

-- Seed Data Barang Awal
INSERT INTO barang (nama_barang, stok, satuan) VALUES
('Kabel FO Dropcore', 125, 'Roll'),
('Modem ONT ZTE', 12, 'Pcs'),
('Pigtail SC-UPC', 50, 'Pcs'),
('Splitter 1:8 ODP', 20, 'Pcs'),
('Klem Penambat Hook', 200, 'Pcs');
`;

async function runMigration() {
  console.log('--- STARTING SUPABASE DDL MIGRATION ---');
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query(ddl);
    await client.query('COMMIT');
    console.log('✅ Migrasi skema database Supabase BERHASIL dieksekusi!');

    // Verify created tables and seeds
    const tablesRes = await client.query(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      ORDER BY table_name;
    `);
    console.log('Tabel terverifikasi:', tablesRes.rows.map(r => r.table_name));

    const usersRes = await client.query('SELECT id, nama_lengkap, role, email FROM users;');
    console.log('Data users:', usersRes.rows);

    const barangRes = await client.query('SELECT * FROM barang;');
    console.log('Data barang:', barangRes.rows);

  } catch (err) {
    await client.query('ROLLBACK');
    console.error('❌ Gagal menjalankan migrasi:', err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

runMigration();
